### ISSUE TITLE
Can I add a new feature which is scroll indicator at the top of navbar?

### ISSUE THREAD

**Issue by yogesh2k21** [pulkithanda/navbars-hf#12]
@pulkithanda Can I add a new feature which is scroll indicator at the top of navbar?

**Comment by yogesh2k21** [comment]
it will look really awesome to ur site

**Comment by pulkithanda** [comment]
Hey @yogesh2k21 Sure mate, Will check ur pr tomorrow (exams) thanks

**Comment by yogesh2k21** [comment]
Ok no problem
